let art = [
  {
    id: "123asdfg98765",
    nftname: "Art #3902",
    image: "../Assets/Images/Art-1.jpeg",
    profile: "../Assets/Images/avatar-8.jpg",
    username: "@streetboy",
    price: "3.5 ETH",
    highestbid: "3.5 ETH",
  },
  {
    id: "1234edxfcvbjt",
    nftname: "Art #3902",
    image: "../Assets/Images/Art-2.jpeg",
    profile: "../Assets/Images/avatar-7.jpg",
    username: "@Cutiegirl",
    price: "3.5 ETH",
    highestbid: "3.5 ETH",
  },
  {
    id: "47976436tygvb",
    nftname: "Art #3902",
    image: "../Assets/Images/Art-3.jpeg",
    profile: "../Assets/Images/avatar-6.gif",
    username: "@Butterfly",
    price: "3.5 ETH",
    highestbid: "3.5 ETH",
  },
  {
    id: "4rtghjnm8uygf",
    nftname: "Art #3902",
    image: "../Assets/Images/Art-4.jpg",
    profile: "../Assets/Images/avatar-5.jpg",
    username: "@streetboy",
    price: "3.5 ETH",
    highestbid: "3.5 ETH",
  },
  {
    id: "bjakwf0987650",
    nftname: "Art #3902",
    image: "../Assets/Images/Art-5.jpg",
    profile: "../Assets/Images/avatar-8.jpg",
    username: "@streetboy",
    price: "3.5 ETH",
    Highestbid: "3.5 ETH",
  },
  {
    id: "05687ytrfch6y",
    nftname: "Art #3909",
    image: "../Assets/Images/Art-6.jpg",
    profile: "../Assets/Images/avatar-8.jpg",
    username: "@streetboy",
    price: "3.5 ETH",
    highestbid: "3.5 ETH",
  },
  {
    id: "690ytgtvucytv",
    nftname: "Art #3902",
    image: "../Assets/Images/Art-7.jpg",
    profile: "../Assets/Images/avatar-8.jpg",
    username: "@streetboy",
    price: "3.5 ETH",
    highestbid: "3.5 ETH",
  },
  {
    id: "ueyf398r7612",
    nftname: "Art #3902",
    image: "../Assets/Images/neymar.png",
    profile: "../Assets/Images/avatar-8.jpg",
    username: "@streetboy",
    price: "3.5 ETH",
    highestbid: "3.5 ETH",
  },
];
// console.log(art);
