let art = [
  {
    nftname: "Art #3902",
    image: "../Assets/Images/Art-1.jpeg",
    profile: "../Assets/Images/avatar-8.jpg",
    username: "@streetboy",
    price: "3.5 ETH",
    highestbid: "3.5 ETH",
  },
  {
    nftname: "Art #3902",
    image: "../Assets/Images/Art-2.jpeg",
    profile: "../Assets/Images/avatar-7.jpg",
    username: "@Cutiegirl",
    price: "3.5 ETH",
    highestbid: "3.5 ETH",
  },
  {
    nftname: "Art #3902",
    image: "../Assets/Images/Art-3.jpeg",
    profile: "../Assets/Images/avatar-6.gif",
    username: "@Butterfly",
    price: "3.5 ETH",
    highestbid: "3.5 ETH",
  },
  {
    nftname: "Art #3902",
    image: "../Assets/Images/Art-4.jpg",
    profile: "../Assets/Images/avatar-5.jpg",
    username: "@streetboy",
    price: "3.5 ETH",
    highestbid: "3.5 ETH",
  },
  {
    nftname: "Art #3902",
    image: "../Assets/Images/Art-5.jpg",
    profile: "../Assets/Images/avatar-8.jpg",
    username: "@streetboy",
    price: "3.5 ETH",
    Highestbid: "3.5 ETH",
  },
  {
    nftname: "Art #3909",
    image: "../Assets/Images/Art-6.jpg",
    profile: "../Assets/Images/avatar-8.jpg",
    username: "@streetboy",
    price: "3.5 ETH",
    highestbid: "3.5 ETH",
  },
  {
    nftname: "Art #3902",
    image: "../Assets/Images/Art-7.jpg",
    profile: "../Assets/Images/avatar-8.jpg",
    username: "@streetboy",
    price: "3.5 ETH",
    highestbid: "3.5 ETH",
  },
  {
    nftname: "Art #3902",
    image: "../Assets/Images/neymar.png",
    profile: "../Assets/Images/avatar-8.jpg",
    username: "@streetboy",
    price: "3.5 ETH",
    highestbid: "3.5 ETH",
  },
];
